# Generated by Django 4.1.7 on 2023-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'command',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('intent_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'intent',
                'managed': False,
            },
        ),
    ]
