# Generated by Django 4.1.7 on 2023-03-24 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('io_username', models.CharField(max_length=255)),
                ('io_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curtain',
            fields=[
                ('c_id', models.OneToOneField(db_column='curtain_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='curtain_child', serialize=False, to='houses.device')),
            ],
            options={
                'db_table': 'curtain',
                'managed': False,
            },
            bases=('houses.device',),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('c_id', models.OneToOneField(db_column='fan_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fan_child', serialize=False, to='houses.device')),
            ],
            options={
                'db_table': 'fan',
                'managed': False,
            },
            bases=('houses.device',),
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('c_id', models.OneToOneField(db_column='light_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='light_child', serialize=False, to='houses.device')),
            ],
            options={
                'db_table': 'light',
                'managed': False,
            },
            bases=('houses.device',),
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('c_id', models.OneToOneField(db_column='watering_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='watering_child', serialize=False, to='houses.device')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'watering',
                'managed': False,
            },
            bases=('houses.device',),
        ),
    ]
